route:
  group_by: ['alertname']  # Group alerts by alert name
  group_wait: 10s          # Wait time before sending the first notification
  group_interval: 5m       # Minimum interval between notifications
  repeat_interval: 1h      # Time after which to resend an alert if it is still firing
  # receiver: 'slack'        # Default receiver
  # routes:
  #   - match:
  #       alertname: 'airflow_service_down'  # Match specific alerts
  #     receiver: 'slack'                    # Route to Slack

# receivers:
#   - name: 'slack'
#     slack_configs:
#       - api_url: ""
#         username: 'Alert Manager'
#         title: "{{ .CommonAnnotations.summary }}"
#         text: "Alert: {{ .CommonAnnotations.description }}"
#         send_resolved: true                   # Send notifications when alerts are resolved
#         channel: '#bi_airflow_notification'
#         icon_url: https://avatars3.githubusercontent.com/u/3380462
