apiVersion: 1

datasources:
  # - name: ClickHouse
  #   type: grafana-clickhouse-datasource
  #   isDefault: true
  #   jsonData:
  #     defaultDatabase: ""
  #     protocol: http
  #     port: 8123
  #     server: clickhouse-node-01
  #     username: clickhouse
  #     tlsSkipVerify: true
  #   secureJsonData:
  #         password: clickhouse

  - name: Prometheus
    type: prometheus
    url: http://prometheus:9090
    isDefault: false
