global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - alert-rules.yml

alerting:
  alertmanagers:
   - static_configs:
     - targets:
        - alertmanager:9093

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  
  # - job_name: 'kafka_jmx'
  #   static_configs:
  #   - targets: [
  #     'kafka-broker-01:27075',
  #     'kafka-broker-02:27075',
  #     'kafka-broker-03:27075',
  #     'kafka-controller-01:26075',
  #     'kafka-controller-02:26075',
  #     'kafka-controller-03:26075',
  #     'kafka-connect-01:25075',
  #     'kafka-connect-02:25075',
  #     'kafka-connect-03:25075',
  #     ]

  # - job_name: 'airflow'
  #   static_configs:
  #   - targets: [
  #     'airflow-statsd:10017',
  #     'airflow-flower:10018'
  #     ]

  - job_name: 'cadvisor'
    dns_sd_configs:
    static_configs:
    - targets: [
      'host-01:9101',
      'host-02:9101'
    ]

  - job_name: 'node-exporter'
    static_configs:
    - targets: [
      'host-01:9100',
      'host-02:9100'
    ]
  
  # - job_name: clickhouse
  #   static_configs:
  #     - targets: [
  #       'clickhouse-node-01:9126',
  #       'clickhouse-node-02:9126'
  #       ]
