version: "3.9"

x-healthcheck-config: &healthcheck-config
  interval: 30s
  timeout: 10s
  retries: 3
  start_period: 40s

x-deploy-on-front: &deploy-on-front
  deploy:
    replicas: 1
    placement:
      constraints:
        - node.hostname == ${HOSTNAME_01}

x-deploy-on-host-01: &deploy-on-host-01
  deploy:
    placement:
      constraints:
        - node.hostname == ${HOSTNAME_01}
x-deploy-on-host-02: &deploy-on-host-02
  deploy:
    placement:
      constraints:
        - node.hostname == ${HOSTNAME_02}
x-deploy-on-host-03: &deploy-on-host-03
  deploy:
    placement:
      constraints:
        - node.hostname == ${HOSTNAME_03}
        
##################################################################

networks:
  data_platform:
    external: true

x-network: &network
  networks:
    - data_platform

services:
  prometheus:
    image: prom/prometheus:v3.9.1
    ports:
      - 9090:9090
    volumes:
      - prometheus-data:/prometheus
    configs:
      - source: prometheus-config
        target: /etc/prometheus/prometheus.yml
      - source: prometheus-alert-rules
        target: /etc/prometheus/alert-rules.yml
    <<: [*network, *deploy-on-front]
    extra_hosts:
      - 'host-01:192.168.100.80'
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9090/-/healthy"]
      <<: *healthcheck-config

  alertmanager:
    image: prom/alertmanager:v0.31.0
    ports:
      - 9093:9093
    configs:
      - source: alertmanager-config
        target: /etc/alertmanager/alertmanager.yml
    <<: [*network, *deploy-on-front]
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9093/-/healthy"]
      <<: *healthcheck-config

  grafana:
    image: grafana/grafana:12.3.2
    ports:
      - 10000:3000
    # volumes:
    #   - grafana-data:/var/lib/grafana
    environment:
        GF_SECURITY_ADMIN_USER: grafana
        GF_SECURITY_ADMIN_PASSWORD__FILE: /run/secrets/GRAFANA_ADMIN_PASSWORD
        GF_USERS_ALLOW_SIGN_UP: 'false'
        GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: grafana-clickhouse-datasource
        GF_SERVER_DOMAIN: meysamaghili.ir
        GF_SERVER_ROOT_URL: https://meysamaghili.ir/grafana
        GF_SERVER_SERVE_FROM_SUB_PATH: "true"
    secrets:
      - GRAFANA_ADMIN_PASSWORD
    <<: [*network, *deploy-on-front]
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3000/api/health || exit 1"]
      <<: *healthcheck-config

  node-exporter:
    image: prom/node-exporter:v1.10.2
    deploy:
      mode: global
    ports:
      - 9100:9100
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.rootfs=/host'
      - '--path.procfs=/host/proc' 
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"    
      # - "^/(rootfs/)?(dev|etc|host|proc|run|sys|volume1)($$|/)"
    <<: *network

  # cadvisor:
  #   image: zcube/cadvisor:v0.45.0
  #   deploy:
  #     mode: global
  #   ports:
  #     - 9101:8080
  #   volumes:
  #     - /:/rootfs:ro
  #     - /var/run:/var/run:rw
  #     - /sys:/sys:ro
  #     - /var/lib/docker/:/var/lib/docker:ro
  #     - /dev/disk/:/dev/disk:ro
  #   <<: *network

volumes:
  prometheus-data:
  grafana-data:

configs:
  alertmanager-config:
    file: ./configs/alertmanager.yml
    name: alertmanager-config_2025-11-14-v1
  prometheus-config:
    file: ./configs/prometheus.yml
    name: prometheus-config_2025-11-14-v1
  prometheus-alert-rules:
    file: ./configs/alert-rules.yml
    name: prometheus-alert-config_2025-11-14-v1

secrets:
  GRAFANA_ADMIN_PASSWORD:
     external: true
